Resources:
  TwitterGlueTable:
    Type: "AWS::Glue::Table"
    Properties:
      DatabaseName: ${self:custom.glue-database}
      CatalogId: "#{AWS::AccountId}"
      TableInput:
        Name: ${opt:stage, self:provider.stage}-${self:service}-table
        TableType: "EXTERNAL_TABLE"
        Parameters: {
                "classification": "csv",
                "typeOfData": "file",
                "columnsOrdered": "true",
                "delimiter": ",",
                "skip.header.line.count": "1"
        }
        PartitionKeys: 
         - Name: year
           Type: integer
         - Name: month
           Type: integer
         - Name: day
           Type: integer
                           
        StorageDescriptor:
          StoredAsSubDirectories: False
          Parameters: {
                  "classification": "csv",
                  "typeOfData": "file",
                  "delimiter": ",",
                  "skip.header.line.count": "1"
          }
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          Columns:
            - Type: string
              Name: id
            - Type: string
              Name: creation_date
            - Type: integer
              Name: line
            - Type: string
              Name: text
 
            
          SerdeInfo:
            Parameters: {
                        "field.delim": ","
            }
            SerializationLibrary: "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
          Compressed: False
          Location: !Sub "s3://${self:custom.raw-bucket}/twitter/"
        
      