Resources:
  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${opt:stage, self:provider.stage}-${self:service}-glue-crawler-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName:  ${opt:stage, self:provider.stage}-${self:service}-glue-crawler-role-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  TwitterCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: ${opt:stage, self:provider.stage}-${self:service}-glue-crawler
      Role: 
        Fn::GetAtt: [ GlueCrawlerRole, Arn ]
        
      DatabaseName: ${self:custom.glue-database}
      Targets:
        S3Targets:
          - Path: ${self:custom.raw-bucket}/twitter/
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"